Protocols.External/[C] CashShopHandler/[b] BuyItems.cs, Protocols.External/[C] CashShopHandler/[g] GiftItemShop.cs, Protocols.External/[l] ExtLevelEditor/[A] TravelToFriend.cs, Protocols.External/[l] ExtLevelEditor/[a] TravelToGroup.cs
Traveling to friends and group leader is now possible. Buy items from the cash mall. Gifting items from cash mall works and correctly gifts item to desired friend, however protocol isnt finished.
=> Add TravelToFriend/Group protocols, add BuyItems protocol for Cash Shop, add GiftItem protocol

Protocols.External/[h] HotbarHandler/[u] UseSlot.cs, Protocols.External/[i] InventoryHandler/[u] UseItem.cs, Protocols.External/[l] ExtLevelEditor/[z] StartPlayLevel.cs, Server.Reawakened/Entities/Components/InterObjStatusComp.cs, Server.Reawakened/Players/Extensions/CharacterInventoryExtensions.cs, Server.Reawakened/Players/Extensions/PlayerDamageExtensions.cs, Server.Reawakened/Players/Extensions/PlayerExtensions.cs, Server.Reawakened/Players/Extensions/PlayerHealExtensions.cs, Server.Reawakened/Players/Models/TemporaryDataModel.cs
Reworked UseSlot and expanded code functionality for all consumable items
=> Consumables rework

Protocols.External/[h] HotbarHandler/[u] UseSlot.cs, Protocols.External/[i] InventoryHandler/[u] UseItem.cs, Protocols.External/[s] Synchronizer/[s] State.cs, Server.Reawakened/Configs/ServerRConfig.cs, Server.Reawakened/Players/Extensions/CharacterExtensions.cs, Server.Reawakened/Players/Models/TemporaryDataModel.cs, Server.Reawakened/Rooms/Models/Entities/BaseCollider.cs
- These changes should fix the Main branch.
=> Fix errors on main

Server.Reawakened/Entities/Components/QuestCollectibleControllerComp.cs, Server.Reawakened/Players/Extensions/NPCExtensions.cs
=> FIx quest collectible bug

Protocols.External/[i] InventoryHandler/[u] UseItem.cs, Web.AssetBundles/Assets/LocalAssets/InternalDialogRewrite.xml
Changes
- Fixed recipes not being removed from inventory
- Fixed Tesen's daily quest dialog name
=> Fix recipes and Tesen's daily quest

Server.Reawakened/Configs/GameVersion.cs, Server.Reawakened/Configs/ServerRConfig.cs, Server.Reawakened/Entities/Components/BreakableEventControllerComp.cs, Web.AssetBundles/Assets/LocalAssets/EditItem.xml, Web.AssetBundles/Assets/LocalAssets/EditVendor.xml, Web.Launcher/Models/LauncherRConfig.cs
Changes
- Fixed some breakables not working
- Changed game versions to be whenever tutorial changes occured
=> Fixed breakables

Server.Reawakened/Entities/Components/BreakableEventControllerComp.cs, Server.Reawakened/Entities/Components/EnemyControllerComp.cs, Server.Reawakened/Entities/Components/SpiderBossControllerComp.cs, Server.Reawakened/Entities/Components/TriggerArenaComp.cs, Server.Reawakened/Entities/Entity/Enemy.cs, Server.Reawakened/Rooms/Extensions/PlayerExtensions.cs, Server.Reawakened/XMLs/Bundles/WorldStatistics.cs
Changes
- Added WorldStatistics xml loader
- Fixed arenas
- Added IsObjectKilled checks to places where IsBroken checks were
=> WorldStatistics

Server.Reawakened/Players/Models/Character/CharacterDataModel.cs, Server.Reawakened/XMLs/Models/Events/EventInfo.cs
Changes
- Added GameVersion check for GuestPass for early 2012
- Fixed Events for late 2012
=> 2012 Fixes

Protocols.External/Protocols.External.csproj, Protocols.External/[b] LocalizationHandler/[s] SetLocale.cs, Server.Reawakened/Players/Models/Character/CharacterDataModel.cs, Server.Reawakened/Players/Models/TemporaryDataModel.cs
Changes
- Added SetLocale protocol
- Fixed CharacterData for early 2012
=> SetLocale protocol

Server.Reawakened/Entities/Components/NPCControllerComp.cs
Changes
- Added dialog status after completing all npc quests
=> Added dialog status after completing all npc quests

Protocols.External/[a] ChatHandler/[e] FreeChat.cs, Server.Reawakened/Network/Extensions/ChatExtensions.cs, Server.Reawakened/Players/Models/Groups/GroupModel.cs, Server.Reawakened/XMLs/Models/Events/EventInfo.cs
Changes
- Added Chat Channels
- Corrected AdFrequency value for EventInfo on 2012
=> Added Chat Channels

Protocols.External/[d] DescriptionHandler/[p] RequestPortalInfo.cs, Web.AssetBundles/Assets/LocalAssets/InternalDialog.xml
Changes
- Fixed portal info/glowing particles not working for 2012
- Added some dialog to Chim Foo NPCs
=> Fixed portals on 2012

Protocols.External/[M] MinigameHandler/[m] FinishMinigame.cs, Server.Reawakened/Chat/Services/ChatCommands.cs, Server.Reawakened/Entities/Components/ChestControllerComp.cs, Server.Reawakened/Entities/Components/StomperControllerComp.cs, Server.Reawakened/Entities/Components/TriggerCoopArenaSwitchControllerComp.cs, Server.Reawakened/Players/Extensions/PlayerExtensions.cs, Server.Reawakened/Rooms/Models/Entities/Colliders/HazardEffectCollider.cs
- Minigames can now be completed in multiplayer.
- Minigame timers will now stop and properly display each players finished time.
- XP bar will now reset upon level up.
- Fixed bug with LevelUp command. Allows players to level themselves down without bugs.
=> Fixed Minigames, XP bar glitch, and other bugs.

Server.Reawakened/Configs/ServerRConfig.cs, Server.Reawakened/Entities/Entity/Enemies/AIStateEnemies/EnemySpiderBoss.cs, Server.Reawakened/Entities/Entity/Enemies/AIStateEnemies/EnemyTeaserSpiderBoss.cs, Server.Reawakened/Rooms/Room.cs, Web.AssetBundles/Assets/LocalAssets/InternalDefaultEnemies.xml
- Quick fix to hitbox of Rachnok in Rachnok's Lair
=> Rachnok's Lair Fix

Server.Reawakened/Entities/Components/NPCControllerComp.cs
Fixed some quest npcs status being updated to dialog too early
=> Fix quest npc status

Web.AssetBundles/Assets/LocalAssets/InternalDialog.xml, Web.AssetBundles/Assets/LocalAssets/InternalVendor.xml
- Corrected names for Plunder Alley npcs to match the original game (Found a source)
- Added missing food vendor Trink to Plunder Alley
=> Quick fix for Plunder Alley

Protocols.External/[s] Synchronizer/[s] State.cs, Server.Reawakened/Configs/ServerRConfig.cs, Server.Reawakened/Entities/AbstractComponents/BaseHazardControllerComp.cs, Server.Reawakened/Entities/Components/EnemyControllerComp.cs, Server.Reawakened/Players/Extensions/PlayerDamageExtensions.cs, Server.Reawakened/Players/Extensions/PlayerHealExtensions.cs, Server.Reawakened/Players/Extensions/PlayerStatusEffectExtensions.cs, Server.Reawakened/Players/Models/TemporaryDataModel.cs, Server.Reawakened/Rooms/Models/Entities/ColliderType/PlayerCollider.cs, Server.Reawakened/Rooms/Models/Entities/Colliders/HazardEffectCollider.cs, Web.AssetBundles/Assets/LocalAssets/InternalLoot.xml
- Removed SendNonCollisionEvent from HazardEffectCollider
- Removed NonCollision check from PlayerCollider
- Fixed inaccurate spiderweb collider positioning
- Added 2nd blue chest to The Volcano Lair (2012)
=> Fixed lag, bugs, missing loot, and healing staff bug

Server.Reawakened/Assets/LocalAssets/InternalDefaultEnemies.xml, Server.Reawakened/Entities/AbstractComponents/BaseHazardControllerComp.cs, Server.Reawakened/Entities/Components/EnemyControllerComp.cs, Server.Reawakened/Entities/Enemies/Enemy.cs, Server.Reawakened/Entities/Enemies/EnemyAi/BehaviorEnemy.cs
- Enemy positions are now always correct
- Fixed the hitboxes of ceiling enemies
- Enemies now apply proper damage when touched
- Enemies now knock back when touched
- Made the pincer hitbox taller
=> Multiple Enemy Hotfixes

Server.Reawakened/Assets/LocalAssets/InternalDefaultEnemies.xml, Server.Reawakened/Entities/Enemies/BehaviorEnemies/Abstractions/BehaviorEnemy.cs, Server.Reawakened/XMLs/Models/Enemy/Models/GlobalPropertyModel.cs, Server.Reawakened/XMLs/Models/Enemy/States/PatrolState.cs
- Enemies no longer teleport back to their spawn position in Patrol state
- Cragcrawler EndPathWaitTime lengthened
- Restored enemy global properties to their intended values
=> Enemy behavior fixes

Server.Reawakened/Players/Extensions/PlayerExtensions.cs
This will set the player tribe to whichever tribe highway they enter first
=> Set tribe on <2014

Server.Reawakened/Entities/Components/BaseSpawnerControllerComp.cs, Server.Reawakened/Entities/Enemies/BehaviorEnemies/Abstractions/AIBaseBehavior.cs, Server.Reawakened/Entities/Enemies/BehaviorEnemies/Abstractions/BehaviorEnemy.cs, Server.Reawakened/Entities/Enemies/BehaviorEnemies/BehaviourTypes/AIBehaviorGrenadier.cs
- Enemies now spawn on their correct parent plane
- Spawners spawn enemies on the same plane as the spawner
=> Fixed enemy plane positioning

Server.Reawakened/Entities/Components/Characters/Controllers/EnemyControllerComp.cs, Server.Reawakened/Entities/Enemies/Extensions/AISyncEventHelper.cs
- Fixed enemies on new framework
=> Enemies spawn again

Protocols.External/[h] HotbarHandler/[r] RemoveSlot.cs, Protocols.External/[h] HotbarHandler/[u] UseSlot.cs, Server.Reawakened/Core/Configs/ItemRConfig.cs, Server.Reawakened/Entities/Components/GameObjects/Spawners/BaseSpawnerControllerComp.cs, Server.Reawakened/Players/Extensions/CharacterInventoryExtensions.cs, Server.Reawakened/Players/Extensions/PlayerExtensions.cs
- Should prevent hotbar slots from randomly disappearing
=> Fixed disappearing hotbar slots bug

Protocols.External/[h] HotbarHandler/[u] UseSlot.cs, Server.Reawakened/Chat/Services/ChatCommands.cs, Server.Reawakened/Entities/Components/GameObjects/Platforms/CollapsingPlatformComp.cs
- Fixed trigger positioning of collapsing platforms
- Fixed tp command
=> Fixed bugs

Protocols.External/[l] ExtLevelEditor/[v] LevelUpdate.cs, Protocols.External/[n] NpcHandler/[h] ChooseQuestReward.cs, Server.Reawakened/Chat/Services/ChatCommands.cs, Server.Reawakened/Core/Configs/ItemRConfig.cs, Server.Reawakened/Entities/Components/GameObjects/Hazards/Abstractions/BaseHazardControllerComp.cs, Server.Reawakened/Entities/Components/GameObjects/Items/ChestControllerComp.cs, Server.Reawakened/Entities/Components/GameObjects/NPC/NPCControllerComp.cs, Server.Reawakened/Entities/Components/GameObjects/Trigger/Abstractions/BaseTriggerCoopController.cs, Server.Reawakened/Entities/Projectiles/MeleeEntity.cs, Server.Reawakened/Players/Extensions/PlayerStatusEffectExtensions.cs, Server.Reawakened/Players/Models/Pets/PetModel.cs, Server.Reawakened/Players/Models/TemporaryDataModel.cs
- Added WebWalker boots
- Implemented automated main quests
- Fixed melee aerial attack ranges
- NPC status will change from Quest to Dialog if quest level requirement exceeds players level
- Reduced slow effect spam
=> Added WebWalker Boots and bug fixes

Protocols.External/[i] InventoryHandler/[e] EquipItem.cs, Server.Reawakened/Core/Configs/ServerRConfig.cs, Server.Reawakened/Entities/Components/GameObjects/Hazards/Abstractions/BaseHazardControllerComp.cs, Server.Reawakened/Entities/Components/GameObjects/Items/ChestControllerComp.cs, Server.Reawakened/Players/Extensions/CharacterInventoryExtensions.cs
- Unequipped items will be added to the players inventory
- Chest of different tiers will give you more bananas and the reward will be doubled if you're level 30+
=> Fixed disappearing items bug & Better chest rewards

Server.Reawakened/Core/Configs/ItemRConfig.cs, Server.Reawakened/Entities/Projectiles/MeleeEntity.cs
- Height of collider has been extended to make it easier to kill enemies from below
- Width of collider has also been extended
- All sides of aerial attack should be the same length making for original functionality
=> Adjusted aerial melee combat AGAIN

Protocols.External/[s] Synchronizer/[s] State.cs, Server.Reawakened/Core/Configs/ItemRConfig.cs, Server.Reawakened/Core/Configs/ServerRConfig.cs, Server.Reawakened/Entities/Components/GameObjects/Hazards/Abstractions/BaseHazardControllerComp.cs, Server.Reawakened/Players/Extensions/PlayerDamageExtensions.cs
- Implemented underwater system
- Fixed bugged sea shell hazards
- [Bug] Using consumables underwater breaks the underwater system preventing the player from being able to drown, will look into soon
=> Implemented underwater system

Protocols.External/[s] Synchronizer/[s] State.cs, Server.Reawakened/Chat/Commands/World/OpenDoors.cs, Server.Reawakened/Entities/Components/Characters/Controllers/Base/States/AIStatePatrolComp.cs, Server.Reawakened/Entities/Components/Characters/Controllers/Drake/DrakeEnemyControllerComp.cs, Server.Reawakened/Entities/Components/Characters/Controllers/Drake/States/AIStateDrakePlacementComp.cs, Server.Reawakened/Entities/Components/GameObjects/Items/Abstractions/BaseChestControllerComp.cs, Server.Reawakened/Entities/Components/GameObjects/Trigger/Abstractions/BaseTriggerCoopController.cs, Server.Reawakened/Entities/Components/GameObjects/Trigger/CutsceneManagerComp.cs, Server.Reawakened/Entities/Components/GameObjects/Trigger/Interfaces/ICoopTriggered.cs, Server.Reawakened/Entities/Components/GameObjects/Trigger/TriggerArenaComp.cs, Server.Reawakened/Entities/Components/GameObjects/Trigger/TriggerReceiverComp.cs, Server.Reawakened/Entities/Enemies/EnemyTypes/BehaviorEnemy.cs, Server.Reawakened/Players/Models/Pets/PetModel.cs
- Fixed daily harvests resetting upon changing level
- Fixed pets holding nonexistent buttons
- Added plane check for enemy detection to prevent enemies from attacking the player on the wrong plane
- Implemented invisibility bomb functionality so enemies can't detect you when invisible
- Implemented Drake patrol state
=> Fixed bugs, implemented drake patrol state

Protocols.External/[Z] PetHandler/[m] UpdatePetMode.cs, Protocols.External/[h] HotbarHandler/[r] RemoveSlot.cs, Protocols.External/[h] HotbarHandler/[s] SetSlot.cs, Protocols.External/[h] HotbarHandler/[u] UseSlot.cs, Protocols.External/[l] ExtLevelEditor/[v] LevelUpdate.cs, Protocols.System/[xml] System/[login] Login.cs, Protocols.System/[xml] System/[logout] Logout.cs, Server.Reawakened/Chat/Commands/Misc/God.cs, Server.Reawakened/Chat/Commands/Misc/LevelUp.cs, Server.Reawakened/Entities/Colliders/Abstractions/BaseCollider.cs, Server.Reawakened/Entities/Components/Characters/Controllers/Base/Abstractions/BaseAIRetreatState.cs, Server.Reawakened/Entities/Enemies/EnemyTypes/Abstractions/BaseEnemy.cs, Server.Reawakened/Players/Extensions/CharacterInventoryExtensions.cs, Server.Reawakened/Players/Extensions/PetAbilityExtensions.cs, Server.Reawakened/Players/Extensions/PlayerExtensions.cs, Server.Reawakened/Players/Models/Misc/TemporaryDataModel.cs, Server.Reawakened/Players/Models/Pets/PetModel.cs
- Implemented pet regeneration system (online and offline)
- Added arg to Trigger method
=> Pet Regeneration

Server.Reawakened/Assets/LocalAssets/InternalLoot.xml
added custom loot tables for Shard Cavern & Hive
=> Shard Caverns loot tables

Server.Reawakened/Entities/Components/GameObjects/NPC/NPCControllerComp.cs
This also fixes the quest from Brento not completing properly and not giving the Spider Boots
=> Fix NPC dialog not appearing due to achievement checks

Server.Reawakened/Assets/LocalAssets/InternalAchievement.xml, Server.Reawakened/Assets/LocalAssets/InternalRecipe.xml, Server.Reawakened/Assets/LocalAssets/InternalVendor.xml, Server.Reawakened/Core/Configs/ItemRConfig.cs
- Fixed achievements so that they won't get completed on their own.
- Changed Guardian Cadet Armour recipe ingredients.
=> Changes to xml files for achievements and recipes

Protocols.External/[n] NpcHandler/[h] ChooseQuestReward.cs, Server.Reawakened/Chat/Commands/Misc/FindPlayer.cs, Server.Reawakened/Chat/Commands/Moderation/Ban.cs, Server.Reawakened/Chat/Commands/Moderation/Kick.cs, Server.Reawakened/Chat/Commands/Moderation/Mute.cs, Server.Reawakened/Chat/Commands/Moderation/UnMute.cs, Server.Reawakened/Chat/Commands/Moderation/Warn.cs, Server.Reawakened/Entities/Components/GameObjects/NPC/NPCControllerComp.cs, Web.Launcher/Controllers/Live/OSX/GamePatcherController.cs, Web.Launcher/Controllers/Live/OSX/LauncherPatcherController.cs, Web.Launcher/Controllers/Live/Win/GamePatcherController.cs, Web.Launcher/Controllers/Live/Win/LauncherPatcherController.cs, Web.Launcher/Models/LauncherRConfig.cs, Web.Launcher/Services/LoadUpdates.cs
- Fixed quest rewards sometimes not being given
- Fixed daily quests not resetting
- Fixed Flit's quest starting the Ice Raider quest line too soon
- Added macOS patcher support (untested but should work, if/when we get a mac client)
- Added moderation commands
=> Quest Fixes

Server.Reawakened/Assets/LocalAssets/InternalDialogRewrite.xml
using Daily_Score01 dup_145 dialog for some of them because it doesn't play a voiced dialog, some of the daily quests are given by girl npcs
=> Fix daily quests
